spring:
  r2dbc:
    url: r2dbc:h2:file:///./tmp/testdb
    username: sa
    password:

  h2.console:
    enabled: true
    path: /h2-console

  datasource:
    url: jdbc:h2:file:./tmp/testdb
    username: sa

  flyway:
    url: jdbc:h2:file:./tmp/testdb
    baseline-on-migrate: true
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}